version: "3.3"
services:
  #web:
  #  container_name: web
  #  build:      
  #    context: ..
  #    dockerfile: ./MoviesAPI/Dockerfile
  #  depends_on: [ mssql ]        
  #  ports:
  #    - "8081:80"
  #web_develop:
  #  container_name: web_development
  #  image: "mcr.microsoft.com/dotnet/sdk:6.0"
  #  depends_on: [ mssql ]
  #  volumes:
  #    - ../:/app
  #  command: dotnet watch --project ./app/MoviesAPI run --urls "http://0.0.0.0:80"    
  #  ports:
  #    - "8082:80"
  mssql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: mssql
    hostname: mssql
    environment:
      SA_PASSWORD: "Pass123!"
      ACCEPT_EULA: "Y"
    restart: unless-stopped    
    ports:
      - "11433:1433"
  mssql_tests:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: mssql_tests
    environment:
      SA_PASSWORD: "Pass123!"
      ACCEPT_EULA: "Y"
    restart: unless-stopped    
    ports:
      - "11455:1433" 